import type { FormConfig } from "../types/formConfig.types";

export const supplierDefaultConfig: FormConfig = {
  tenantId: "default",
  entityType: "supplier",
  updatedAt: new Date(0).toISOString(),
  sections: [
    {
      id: "base-info",
      title: "Informacion basica",
      enabled: true,
      order: 1,
      fields: [
        {
          id: "fullName",
          label: "Nombre / Razon social",
          fieldType: "text",
          required: true,
          editable: true,
          baseField: true,
          order: 1,
        },
        {
          id: "documentType",
          label: "Tipo de documento",
          fieldType: "select",
          required: true,
          editable: true,
          baseField: true,
          order: 2,
          options: [
            { label: "NIT", value: "NIT" },
            { label: "RUT", value: "RUT" },
            { label: "CC", value: "CC" },
          ],
        },
        {
          id: "documentNumber",
          label: "Numero de documento",
          fieldType: "text",
          required: true,
          editable: false,
          baseField: true,
          order: 3,
        },
        {
          id: "address",
          label: "Direccion",
          fieldType: "text",
          required: true,
          editable: true,
          baseField: true,
          order: 4,
        },
        {
          id: "phone",
          label: "Celular / Telefono",
          fieldType: "phone",
          required: true,
          editable: true,
          baseField: true,
          order: 5,
        },
        {
          id: "email",
          label: "Correo electronico",
          fieldType: "email",
          required: true,
          editable: true,
          baseField: true,
          order: 6,
        },
      ],
    },
    {
      id: "supplier-info",
      title: "Informacion de proveedor",
      enabled: true,
      order: 2,
      fields: [
        {
          id: "category",
          label: "Categoria",
          fieldType: "select",
          required: true,
          editable: true,
          baseField: true,
          order: 1,
          options: [
            { label: "Bienes", value: "goods" },
            { label: "Servicios", value: "services" },
            { label: "Ambos", value: "both" },
          ],
        },
        {
          id: "paymentTerms",
          label: "Terminos de pago",
          fieldType: "text",
          required: true,
          editable: true,
          baseField: true,
          order: 2,
        },
        {
          id: "bankName",
          label: "Banco",
          fieldType: "text",
          required: true,
          editable: true,
          baseField: true,
          order: 3,
        },
        {
          id: "accountType",
          label: "Tipo de cuenta",
          fieldType: "select",
          required: true,
          editable: true,
          baseField: true,
          order: 4,
          options: [
            { label: "Ahorros", value: "savings" },
            { label: "Corriente", value: "checking" },
          ],
        },
        {
          id: "accountNumber",
          label: "Numero de cuenta",
          fieldType: "text",
          required: true,
          editable: true,
          baseField: true,
          order: 5,
        },
      ],
    },
  ],
};
